pokus/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path


# this is probably obsolete
# it was used together with path(.., .., js_info_dict, name=..) but this doesn't work now (js is dead)
#   https://code.djangoproject.com/ticket/5494
#   https://stackoverflow.com/questions/1963517/how-to-give-package-names-to-django-javascript-catalog-view
#   https://stackoverflow.com/questions/19625102/django-javascript-translation-not-working
'''
js_info_dict = {
    'domain': 'djangojs',
    'packages': ('pokus1',),  # ('pokus1', 'pokus2')
}
'''

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include(('pokus1.urls', 'pokus1'), namespace='pokus1')),
    path('europe', include(('pokus2.urls', 'pokus2'), namespace='pokus2')),
)

pokus1/urls.py
from django.urls import path
from django.views.i18n import JavaScriptCatalog

from .views import HelloWorldView


app_name = 'pokus1'  # make possible use {% url 'pokus1:..' %}
# however this is maybe deprecated; you can achieve same in include(), see project level urls.py

urlpatterns = [
    path('jsi18n/pokus1/', JavaScriptCatalog.as_view(), name='javascript-catalog'),  # /pokus1/: unique app url, probably important
    path('', HelloWorldView.as_view(), name='hello')
]

pokus2/urls.py
from django.urls import path
from django.views.i18n import JavaScriptCatalog

from .views import HelloWorldView


app_name = 'pokus2'   # make possible use {% url 'pokus2:..' %}
# however this is maybe deprecated; you can achieve same in include(), see project level urls.py

urlpatterns = [
    path('jsi18n/pokus2/', JavaScriptCatalog.as_view(), name='javascript-catalog'),  # /pokus2/: unique app url, probably important
    path('', HelloWorldView.as_view(), name='hello')
]

pokus1/models.py
from django.db import models


class Castle(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

pokus2/models.py
from django.db import models


class Castle(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

pokus1/views.py
from django.views.generic import TemplateView


class HelloWorldView(TemplateView):
    template_name = "pokus1/helloworld.html"

pokus2/views.py
from django.views.generic import TemplateView


class HelloWorldView(TemplateView):
    template_name = "pokus2/helloworld.html"

pokus1/templates/pokus1/helloworld.html
{% load trans from i18n %}
{% load static from static %}

{% block extrahead %}
    <script src="{% url 'pokus1:javascript-catalog' %}"></script>
        {# pokus1: is not required here but if we want write it then app_name must be in urls.py #}
    <script src="{% static 'pokus1/js/helloworld.js' %}"></script>
{% endblock %}

{% block content %}
    {% trans "Hello World!" %}
{% endblock %}

pokus2/templates/pokus2/helloworld.html
{% load trans from i18n %}
{% load static from static %}

{% block extrahead %}
    <script src="{% url 'pokus2:javascript-catalog' %}"></script>
        {# pokus2: is not required here but if we want write it then app_name must be in urls.py #}
    <script src="{% static 'pokus2/js/helloworld.js' %}"></script>
{% endblock %}

{% block content %}
    {% trans "Hello Europe!" %}
{% endblock %}